# This file is machine-generated - editing it directly is not advised

julia_version = "1.10.4"
manifest_format = "2.0"
project_hash = "56d36fb09285ef39d0b5039ebc62c65b6569f79d"

[[deps.ASP]]
path = ".."
uuid = "787491fc-541a-4303-b5b6-89ef4c764caf"
version = "1.0.0-DEV"
